### ISSUE TITLE
BloomFilter

### ISSUE THREAD

**Issue by ETHSev** [Mizogg/Mizogg-Tools#10]
hello i need help
i have this problems 
0it [00:00, ?it/s] Please with Database Loading.....
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/Trash/files/Mizogg-Tools/Miz_Tools.py", line 111, in <module>
    bloom_filter1 = BloomFilter.load(fp)   
NameError: name 'BloomFilter' is not defined
0it [00:00, ?it/s]

**Comment by Mizogg** [comment]
Hi Please make sure that you have both pip install simplebloomfliter and 
pip install bitarray==1.9.2 installed. The the same folder as the Miz_Tools.py you need a folder named BF with a Bitcoin and Eth database files. These files needed the be named btc.bf and eth.bf. I hope this helps
