### ISSUE TITLE
Option 21 mizogg tool

### ISSUE THREAD

**Issue by Huntarh** [Mizogg/Mizogg-Tools#11]
Hello sir, sorry to bother you. I am not really good with python coding that's is why I am sending these messages if I knew python coding I would have edited the code myself.

If you check the first video Below you will see the private key recovery working. 

Can you Please make option 21 work like that or can you write a separate python code that will loop the missing characters.

For example, if a user says that 15 characters is missing, all the Missing characters
Should be looped fast beginning from the first to the end of the said missing characters (Like the video below).

Please help me

![ezgif-3-dbd0978ecd](https://user-images.githubusercontent.com/107959503/176242829-3a473987-e680-4113-b452-95dce6641f9e.gif)

Thank you, and please don't be offended by my  questions.

**Comment by Mizogg** [comment]
Hi I wish I could help. But I don't know how to add  that feature. Still learning and do this in spare time for fun. What you ask for is already out there. https://github.com/phrutis/WifSolverCuda >

I would like more to fork and improve my program so I can see how I can improve my skills.  Some one out there might be able to help add this feature but for now I can't.
