### ISSUE TITLE
Control

### ISSUE THREAD

**Issue by Huntarh** [Mizogg/Mizogg-Tools#13]
Sorry to bother, this is my last question. I just wanted to know where in the python code controls the rotation of the first two characters in the circled part of the video below is located in the python script, from there I can tell some to help me edit the code.

https://user-images.githubusercontent.com/107959503/176551770-96e2c99a-9848-4835-b0ef-4cd99e8579f6.mp4

Please can you share a screenshot of the python code that controls the rotation of the characters.

**Comment by Mizogg** [comment]
I have a Github https://github.com/Mizogg/BITCOIN-WIF-Recovery where I added this to the Tools.  You will be able to see the code https://github.com/Mizogg/BITCOIN-WIF-Recovery/blob/main/WIF_Recovery_V2.py

It would be easier to edit BITCOIN-WIF-Recovery I might have a look at this to see if I can make any improvements.
