### ISSUE TITLE
 Add a check on BTC forks.

### ISSUE THREAD

**Issue by Mir0n0v** [Mizogg/Mizogg-Tools#16]
Dear Mizzogg!
Please add the verification of Bitcoin forks: BCH, Bitcoin SV
, BTG, etc. in the "Option 7" menu. If possible. Thanks.

**Comment by Mizogg** [comment]
Hi Mir0m0v,
I might try and add in next versions. But the main API I was using in older versions of the Tools is now not working and the newer one is limited to results and certain types of Cryptos.  
Lets see what happens in next version....
