### ISSUE TITLE
BRUH

### ISSUE THREAD

**Issue by boldofyoutoassume** [Mizogg/Mizogg-Tools#18]
Traceback (most recent call last):
  File "/home/bamboozled/Mizogg-Tools/Miz_tools_OLD_version/Miz_Tools_ice_colour.py", line 11, in <module>
    import secp256k1 as ice
ModuleNotFoundError: No module named 'secp256k1'
bamboozled@FuckeryBox:~/Mizogg-Tools/Miz_tools_OLD_version$ python
Python 2.7.18 (default, Jul 14 2021, 08:11:37) 
[GCC 10.2.1 20210110] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import secp256k1 as ice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named secp256k1
>>> import ice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ice
>>> 

I'm clueless as to what to do next my guy, I already tried importing the module on python; as well as tried to install it thru pip AND pip3 but to no avail. 
does thou maybe know thy solution to this perplexing puzzle?

**Comment by Mizogg** [comment]
You need to have these files in the same folder to run. You can get them from https://github.com/iceland2k14/secp256k1
