### ISSUE TITLE
What about Linux 

### ISSUE THREAD

**Issue by isaacfth** [Mizogg/Mizogg-Tools#21]
Hi, does it work on a Linux terminal, I download it but didn't find the right command to run it. Thank you.

**Comment by Mizogg** [comment]
Hi, Yes it should work in Linux with no problems. Make sure you have the files a folders all correct. Newest Version of Python and all necessary libraries required. I only have add a bat file to make it easier to install libraries needed in Windows. When running Linux it should be the same commands.
pip install bit
pip install rich
pip install base58
pip install simplebloomfilter
pip install bitarray==1.9.2
pip install pyTelegramBotAPI
pip install httplib2

Linux needs additions install I think install these first.
sudo apt install -y python3-pip
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
