### ISSUE TITLE
Command Help

### ISSUE THREAD

**Issue by isaacfth** [Mizogg/Mizogg-Tools#22]
What command can I use in the Linux terminal to make the main menu of the Mizoog tool appear on my screen?

**Comment by Mizogg** [comment]
As long as you have installed all libraries and have the most recent version of python it should work fine . Use pip3 install (library Name).  For example pip3 install hdwallet or pip3 install bip32utils

![image](https://github.com/Mizogg/Mizogg-Tools/assets/88630056/e7e0cc00-1fa0-4ccf-87be-67fb7858201d)
