### ISSUE TITLE
how do you convert the wallets so they can be seen for the btc.BF file

### ISSUE THREAD

**Issue by smartazz220** [Mizogg/Mizogg-Tools#24]
im not to sure how to convert the addresses for that file I have tried hash 160 but I am just not 100% sure how to add more addresses

**Comment by Mizogg** [comment]
HI You need CBloom.py which converts a txt database to a bloomfilter database. You can find a copy here https://github.com/Mizogg/Tkinter-Power/blob/main/files/Cbloom.py or Join Telegram for more information. https://t.me/CryptoCrackersUK 
Or if you want Bloomfilter database for all type, a group here creates them all https://t.me/Blockchain_BTC_ETH_DUMPS
