### ISSUE TITLE
Mizogg tool 10

### ISSUE THREAD

**Issue by Handsomekaizer** [Mizogg/Mizogg-Tools#5]
Hello sir I like your tools but I wanted to make a recommendation, please can you make it possible for users to check Bitcoin WIF from a .txt file on number 10, of the tool.
Because I lost my WIF so I wanted to create random characters, put them in a .txt file and check whether any will match
Thanks

**Comment by Mizogg** [comment]
I I'm sorry Don't know right now how I can add I have quite a few programs with different options but none that can do WIF faster. maybe try other GitHub programs. I have been told   FinderOuter can find a win with 10 characters missing at the end in less than 5 minutes.

**Comment by Handsomekaizer** [comment]
Sorry but the 

> Added WIF LIST to option 10

Sorry to bother, but I used the updated code to convert WIF.txt file to address it worked but the problem is that it doesn't show the balance of the converted address. Please help this one last time.

**Comment by Mizogg** [comment]
Hi I can confirm that it does check for balance when converting your WIF.txt on option 10  .WIF to Bitcoin Address with Balance Check.
