### ISSUE TITLE
Number 21

### ISSUE THREAD

**Issue by Huntarh** [Mizogg/Mizogg-Tools#7]
Hello,
thank you for this great tool. Although I have an issue with number 21 of this tool, the problem is that is is slow and only runs 2 characters in front. For example I am trying to recover a private key with 15 characters missing, it is going to take very long to recover the private key. I would like it if you could make it run the specified missing characters like in the gif below.
For example if the user specifies that 15 characters is missing, this program should run all the 15 alphanumeric characters at once in the missing place and not one after the other. Thanks

![gna](https://user-images.githubusercontent.com/107959503/174910190-6427ef5f-4c30-4f93-a002-3a5715b0c281.gif)

**Comment by Mizogg** [comment]
Please try the first option on 21 and edit the lines c1-c64 magic random.
Fill in your already known private key parts and get it to random scan the
missing characters.  I have example already c1 to c3 with 0  as you will
see if you have tried scanning with that option. Please let me know if you
want me to send any pics or more information

**Comment by Huntarh** [comment]
Sorry you are talking about number 22, I was talking about number 21 which is Bitcoin private key recovery (the private key starts with 5K, not in Hex)
I wanted you to make the missing characters to rotate randomly from the beginning of the missing private key to the end of the missing key characters

**Comment by Mizogg** [comment]
Your 100 % correct yes sorry I miss understood. At the moment I don't know how I can do that with the WIF. I currently working on something that may help. Will update you once it is figured out.

**Comment by Huntarh** [comment]
Ok thanks, Please do I really need it, if you update it please let me know

**Comment by Huntarh** [comment]
Hello sir, sorry to bother you. I am not really good with python coding that's is why I am sending these messages if I knew python coding I would have edited the code myself.
If you check the first video you will see how the private key recovery works and the first two alphanumeric characters(in the red circle) that moves fast in front of the missing private key.
https://user-images.githubusercontent.com/107959503/175546207-5335c586-fcf2-4161-8db9-638516c25237.mp4
Now what I wanted you to edit in the code can be seen circled in the second video.
I wanted you to edit the code and make all the 11111111 missing private key characters to randomize fast like in the circled part in the first video.

https://user-images.githubusercontent.com/107959503/175547304-d4c5b9a5-46fa-42f3-bb88-e547d88e109b.mp4

Thank you, and please don't be offended by my issues
